project_name: pass-cli

builds:
  - id: linux-x86_64
    goos: [ linux ]
    goarch: [ amd64 ]
    binary: pass-cli
    # We are using a CI-generated binary
    skip: true

  - id: linux-arm
    goos: [ linux ]
    goarch: [ arm64 ]
    binary: pass-cli
    # We are using a CI-generated binary
    skip: true

nfpms:
  - id: linux-packages
    package_name: proton-pass-cli
    vendor: Proton AG
    homepage: https://proton.me/pass
    maintainer: Proton Pass Team <idteam@proton.ch>
    description: |
      Proton Pass command-line interface.
      A secure password manager and digital vault from Proton.
    license: GPL-3.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    file_name_template: "{{ .ConventionalFileName }}"
    contents:
      - src: "{{ .Env.BINARY_PATH }}"
        dst: /usr/bin/pass-cli
        file_info:
          mode: 0755
    version_metadata: git
    section: utils
    priority: optional
    deb:
      lintian_overrides:
        - statically-linked-binary

archives:
  # Disable default archives since we're only using nfpms
  - format: binary
    name_template: "{{ .Binary }}"

checksum:
  name_template: 'checksums.txt'

release:
  disable: true
